spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: http://localhost:8085
          predicates:
            - Path=/user-service/*
        - id: check-service-route
          uri: http://localhost:8086
          predicates:
            - Path=/check-service/*
        - id: payment-service-route
          uri: http://localhost:8086
          predicates:
            - Path=/payment-service/*
        - id: payment-service-route
          uri: http://localhost:8086
          predicates:
            - Path=/helper-service/*
server:
  port: 9000
  forward-headers-strategy: framework
