eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_TEST_IP}:${EUREKA_TEST_PORT}/eureka/
    instance:
      prefer-ip-address: true
      
logging:
  level:
    org.springframework.boot.autoconfigure.logging.AutoConfigurationReportLoggingInitializer: DEBUG
