spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sabexzero/identics
          search-paths:
            - backend/java/configuration/global/dev/kafka
            - backend/java/configuration/global/dev/eureka
            - backend/java/configuration/global/dev/open-telemetry
            - backend/java/configuration/microservices/dev
          default-label: dev
          username: sabexzero
          password: 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
server:
  port: 8000