spring:
  opentelemetry:
    traces:
      exporter:
        otlp:
          endpoint: http://${OPENTELEMETRY_TEST_IP}:${OPENTELEMETRY_TEST_PORT}
      sampler:
        probability: 1.0
  metrics:
    export:
      otlp:
        enabled: true
        endpoint: http://${OPENTELEMETRY_TEST_IP}:${OPENTELEMETRY_TEST_PORT}
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    prometheus:
      enabled: true
